   
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
branches:
  only:
    - master
node_js:
  - "10"
dist: trusty
env:
 - NODE_ENV=ci
services: 
 - mysql
cache:
  directories:
    - node_modules

install:
  - npm install
script: "npm run-script test-cover"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"