const componentStates = {
	STOPPED: "STOPPED",
	PENDING: "PENDING",
	INITIALIZED: "INITIALIZED",
	IDLE: "IDLE",
	STARTING: "STARTING",
	STARTED: "STARTED",
	FAILED: "FAILED"
};

const blastModelStates = {
	BLAST_FIRING: "BLAST_FIRING",
	BLAST_FIRED: "BLAST_FIRED",
	BLAST_TIMER_COMPLETE: "BLAST_TIMER_COMPLETE",
	BLAST_DATA_COMPLETE: "BLAST_DATA_COMPLETE",
	BLAST_TERMINATED: "BLAST_TERMINATED"
};

module.exports = { blastModelStates, componentStates };
