const eventServiceLogTypes = {
	UNIT_INSERT: "UNIT_INSERT",
	DET_INSERT: "DET_INSERT",
	UNIT_UPDATE: "UNIT_UPDATE",
	DET_UPDATE: "DET_UPDATE",
	UNIT_COUNT: "UNIT_COUNT",
	EDD_SIG: "EDD_SIG",
	BLAST_EVENT: "BLAST_EVENT"
};

const unitTypes = {
	CONTROL_UNIT: 0,
	SECTION_CONTROLLER: 1,
	BOOSTER_T1: 2,
	BOOSTER_T2: 3,
	EDD: 4,
	CFC: 5
};

const systemModeTypes = {
	AXXIS100: "AXXIS100",
	AXXIS100_CFC: "AXXIS100_CFC",
	AXXIS500: "AXXIS100_CFC",
	AXXIS500_WIFI: "AXXIS500_WIFI",
	AXXIS500_CFC: "AXXIS500_CFC",
	HYDRA: "HYDRA",
	IBS: "IBS"
};

module.exports = {
	unitTypes,
	eventServiceLogTypes,
	systemModeTypes
};
