const blastModelStates = {
	BLAST_FIRING: "BLAST_FIRING",
	BLAST_FIRED: "BLAST_FIRED",
	BLAST_TIMER_COMPLETE: "BLAST_TIMER_COMPLETE",
	BLAST_TIMER_COMPLETE_BYPACKET: "BLAST_TIMER_COMPLETE_BYPACKET",
	BLAST_DATA_COMPLETE: "BLAST_DATA_COMPLETE",
	BLAST_TERMINATED: "BLAST_TERMINATED",
};

const blastUnitStates = {
	DISARMED: "DISARMED",
	ARMED: "ARMED",
	EXCLUDED: "EXCLUDED",
};

module.exports = { blastModelStates, blastUnitStates };
