const { unitTypes } = require("../../constants/typeConstants");
const fields = require("../fields/fieldConstants");

const dataBits = {
	[unitTypes.CONTROL_UNIT]: {
		0: fields.keySwitchStatus,
		1: fields.isolationRelay,
		2: fields.fireButton,
		3: fields.cableFault,
		4: fields.earthLeakage,
		5: null,
		6: fields.blastArmed,
		7: null,
	},
	[unitTypes.SECTION_CONTROLLER]: {
		0: fields.keySwitchStatus,
		1: fields.isolationRelay,
		2: fields.blastArmed,
		4: fields.earthLeakage,
		5: null,
		6: null,
		3: fields.cableFault,
		7: null,
	},
	[unitTypes.BOOSTER_T1]: {
		7: null,
		6: fields.missingPulseDetected,
		5: fields.partialBlast,
		4: fields.boosterFired,
		3: fields.mains,
		2: fields.detonatorStatus,
		1: fields.keySwitchStatus,
		0: fields.dcSupplyVoltage,
	},
	[unitTypes.BOOSTER_T2]: {
		0: null,
		1: null,
		2: null,
		3: null,
		4: null,
		5: fields.isolationRelay,
		6: fields.lfs,
		7: fields.blastArmed,
		8: fields.tooLowBat,
		9: fields.lowBat,
		10: fields.dcSupplyVoltage,
		11: fields.shaftFault,
		12: fields.mains,
		13: fields.earthLeakage,
		14: fields.cableFault,
		15: fields.keySwitchStatus,
	},
	[unitTypes.EDD]: {
		0: null,
		1: fields.bridgeWire,
		2: fields.calibration,
		3: fields.program,
		4: fields.boosterFired,
		5: fields.tagged,
		6: fields.comm,
		7: fields.logged,
	},
	[unitTypes.CFC]: {
		0: fields.min2,
		1: fields.min7,
		2: fields.cableFault,
		3: fields.elt,
		4: null,
		5: null,
		6: null,
		7: fields.deviceType,
	},
};

module.exports = { dataBits };
